FROM pypy:3-7-stretch as builder

RUN apt-get update && apt-get install -y g++ pypy-zmq libffi-dev
COPY . /src
WORKDIR /src
RUN pip install .

FROM pypy:3-7-stretch

RUN apt-get update && \
    apt-get install -y pypy-zmq
#RUN adduser -s /bin/false -D locust
RUN useradd -ms /bin/bash locust
COPY --from=builder /usr/local/site-packages /usr/local/site-packages
COPY --from=builder /usr/local/bin/locust /usr/local/bin/locust
COPY docker_start.sh docker_start.sh
RUN chmod +x docker_start.sh

EXPOSE 8089 5557 5558

USER locust
CMD locust
